name: Update Resource Pack Hashes

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  gen-hashes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Install Node v12
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Zip Resource Pack Variants
        run: |
          mkdir -p $GITHUB_WORKSPACE/target
          cd "$GITHUB_WORKSPACE/resourcepack/variant 1/sd/"
          zip -Xr $GITHUB_WORKSPACE/target/EmojiChat.1.SD.ResourcePack.zip *
          cd "$GITHUB_WORKSPACE/resourcepack/variant 1/hd/"
          zip -Xr $GITHUB_WORKSPACE/target/EmojiChat.1.HD.ResourcePack.zip *
          cd "$GITHUB_WORKSPACE/resourcepack/variant 2/sd/"
          zip -Xr $GITHUB_WORKSPACE/target/EmojiChat.2.SD.ResourcePack.zip *
          cd "$GITHUB_WORKSPACE/resourcepack/variant 2/hd/"
          zip -Xr $GITHUB_WORKSPACE/target/EmojiChat.2.HD.ResourcePack.zip *
      - name: Generate Hashes
        run: node automation/genHashes.js
      - name: Commit Updates
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: plugin/src/main/resources/hash.*.txt
          commit_message: update resource pack hashes
