name: Build and Upload Release Packages
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn package --file pom.xml -Dmaven.wagon.http.ssl.insecure=true
    - name: Zip Resource Pack Variants
      run: |
        cd "$GITHUB_WORKSPACE/resourcepack/variant 1/sd/"
        zip -r $GITHUB_WORKSPACE/target/EmojiChat.1.SD.ResourcePack.zip *
        cd "$GITHUB_WORKSPACE/resourcepack/variant 1/hd/"
        zip -r $GITHUB_WORKSPACE/target/EmojiChat.1.HD.ResourcePack.zip *
        cd "$GITHUB_WORKSPACE/resourcepack/variant 2/sd/"
        zip -r $GITHUB_WORKSPACE/target/EmojiChat.2.SD.ResourcePack.zip *
        cd "$GITHUB_WORKSPACE/resourcepack/variant 2/hd/"
        zip -r $GITHUB_WORKSPACE/target/EmojiChat.2.HD.ResourcePack.zip *
    - name: Upload Plugin Jar
      uses: skx/github-action-publish-binaries@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: 'target/EmojiChat.jar'
    - name: Upload Resource Pack Variant Zips
      uses: skx/github-action-publish-binaries@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: 'target/EmojiChat.*.ResourcePack.zip'

